### ISSUE TITLE
self.pos_dim = config_dict["pos2id"] is missing

### ISSUE THREAD

**Issue by seona0111** [WeijiaLau/MHCH-DAMI#1] opened 2021-11-24 02:50 UTC
It doesn't work properly.
I replaced self.pos_dim=52 (I guess it would be 52)
However it still make errors. 
tensorflow.python.framework.errors_impl.InvalidArgumentError: seq_lens(45) > input.dims(1)
	 [[{{node sent_encoding/bidirectional_rnn/bw/ReverseSequence}}]]

please check the error. 
(I need to know the value of pos_dim)

**Comment by WeijiaLau** [comment] 2021-11-24 05:39
Thanks for your issues.

Yes, the value of pos_dim is 52. I'm sorry for the mistake.

I have updated the model config file by adding the pos2id value. Other files have also been updated without changing the training procedure. And I have checked the codes can run properly. 

```
{...
"pos2id": 52,
...
}
```

Please update the codes. If there are still problems with reproducing the model, please let me know :)

**Comment by seona0111** [comment] 2021-11-24 07:31
Thank you for your feedback.
However, there are still errors
please check below error messages
(I couldn't run data_preprocessing.py because of missing data. So, I just run main.py )

Traceback (most recent call last):
  File "/nlp2/users/MHCH-DAMI/main.py", line 196, in <module>
    main()
  File "/nlp2/users/MHCH-DAMI/main.py", line 166, in main
    is_val=is_val, is_test=is_test, save_best=save_best, ways=args.ways)
  File "/nlp2/users/MHCH-DAMI/main.py", line 190, in train
    is_val=is_val, is_test=is_test, save_best=save_best)
  File "/nlp2/users/MHCH-DAMI/Network.py", line 336, in train
    feed_dict)
  File "/home/6/.conda/envs/test_mhch/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/6/.conda/envs/test_mhch/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/6/.conda/envs/test_mhch/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/6/.conda/envs/test_mhch/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: seq_lens(2) > input.dims(1)
	 [[node sent_encoding/bidirectional_rnn/bw/ReverseSequence (defined at nlp2/users/MHCH-DAMI/Network.py:236) ]]

Errors may have originated from an input operation.
Input Source operations connected to node sent_encoding/bidirectional_rnn/bw/ReverseSequence:
 Reshape_3 (defined at nlp2/users/MHCH-DAMI/networks/DAMI.py:80)	
 concat (defined at nlp2/users/MHCH-DAMI/networks/DAMI.py:85)

**Comment by WeijiaLau** [comment] 2021-11-24 08:17
Hello, I couldn't reproduce the error you encountered. I just clone the newest project and run the main.py directly in tensorflow-gpu==1.15. No error occurs...

Is it possible that the error is caused by an inconsistent environment?

**Comment by seona0111** [comment] 2021-11-30 08:22
I removed the folder, and I cloned the newest proejct and run the main.py
But, there are still errors. I guess it is about dimension problem.
(tensorflow.python.framework.errors_impl.InvalidArgumentError: seq_lens(45) > input.dims(1))
Please check below error messages 

sers/ss/MHCH-DAMI/data/clothing/train.pkl successfully!
Processing::   0%|                                       | 0/22 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: seq_lens(45) > input.dims(1)
         [[{{node sent_encoding/bidirectional_rnn/bw/ReverseSequence}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 196, in <module>
    main()
  File "main.py", line 166, in main
    is_val=is_val, is_test=is_test, save_best=save_best, ways=args.ways)
  File "main.py", line 190, in train
    is_val=is_val, is_test=is_test, save_best=save_best)
  File "/nlp2/users/ss/MHCH-DAMI/Network.py", line 336, in train
    feed_dict)
  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)

  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 3834, in reverse_sequence
    name=name)
  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 8481, in reverse_sequence
    seq_dim=seq_dim, batch_dim=batch_dim, name=name)
  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/6/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by WeijiaLau** [comment] 2021-11-30 14:45
Hi, sorry about this error. I still cannot reproduce this issue.

But according to the error messages, I searched for similar solutions. I guess it may be caused by the sentence length of every utterance. We restrict the utterance to 0-50 words but do not adjust the length stat input to `sequence_length` of bilstm. Can you try this in the data_loader.py? By restricting the sequence length up to 50 when feeding into bilstm for sentence encoding.

Add function into data_loader.py:

```
@staticmethod
    def cut_sent_len(lens_list, max_len=50):
        new_lens_list = []
        for tmp_lens in lens_list:
            tmp_new_lens = []
            for tmp in tmp_lens:
                tmp_new_lens.append(tmp if tmp < max_len else 50)
            new_lens_list.append(tmp_new_lens)
        return new_lens_list
```

Then we modify the 
`sent_len = self.dialogues_sent_len_list `
 in the `data_generator_m` to: 
`sent_len = self.cut_sent_len(self.dialogues_sent_len_list)`

Please try this~

**Comment by WeijiaLau** [comment] 2021-12-09 03:40
I have reproduced the same errors on a new server. And it can be fixed by the length restriction function added to the sentence length list as we have mentioned above:

```
@staticmethod
def cut_sent_len(lens_list, max_len=50):
    new_lens_list = []
    for tmp_lens in lens_list:
        tmp_new_lens = []
        for tmp in tmp_lens:
            tmp_new_lens.append(tmp if tmp < max_len else 50)
        new_lens_list.append(tmp_new_lens)
    return new_lens_list
```
I have updated the project. Thank you for issuing about this error.

**Closed as completed by WeijiaLau** 2021-12-09 03:40 UTC
